apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://host.docker.internal:8443  # Replace with your API server address
    insecure-skip-tls-verify: true             # Skip cert checks (dev only)
  name: local-cluster
contexts:
- context:
    cluster: local-cluster
    user: jenkins
  name: jenkins-context
current-context: jenkins-context
users:
- name: jenkins
  user:
    token: PLACE_YOUR_SERVICEACCOUNT_TOKEN_HERE
