apiVersion: v1
kind: Service
metadata:
  name: goapp-service
spec:
  selector:
    app: goapp
  type: NodePort  # can switch to LoadBalancer or ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080  # Accessible at http://<node-ip>:30080
